### ISSUE TITLE
viper.config and cake.confg are NOT the same thing

### ISSUE THREAD

**Issue by j-griffith** [NetApp/cake#54]
Cake uses a config file specified by `--config` for it's engine, at the same time cobra enables the option to use a config file to specify all of the flags that are configured for the application in a config file.  These two files are not the same thing though.

PR #38 added a set to the viper config variable, which was left out as an option in our case to avoid this conflict.  Clearly, my choice of `--config` as a flag to specify the deployment config was a bad move.  This should be changed to something more specific like "cake-config" or something unique.  That would also be nice because then we can use the power of cobra/viper and specify the command line flags from a yaml config (eg ~/.cobra).

**Comment by bgentry-ntap** [comment]
Looks like we do have values that overlap though. For example, Local and EngineType

**Comment by j-griffith** [comment]
Yeah, should be pretty easy to fix up, couple tweaks and some clarifying docs and we should be good; I think I have it sorted out; just trying to fix up the actual genconfig resultant yaml because at this point it's pretty much useless

**Comment by bgentry-ntap** [comment]
#58 closes this
