### ISSUE TITLE
Config - Local key isn't working

### ISSUE THREAD

**Issue by hulquest** [NetApp/cake#55]
I have been playing with the rke deployment and noticed the Local flag isn't working.  Deployments with true and false values result in the same deployment.

**Comment by bgentry-ntap** [comment]
Are you referring to the Local flag in the yaml config or specifying the --local flag to the cli? I believe the CLI flag overrides the config.yaml

**Comment by hulquest** [comment]
I've been playing with the kvp in the config file.
`LocalOnly = true` 

I can try out the flag.

**Comment by hulquest** [comment]
:suspect: I corrected my misuse of LocalOnly.  Was going from memory instead of just pulling up the example
