### ISSUE TITLE
Provide the ability to specify your own OVA

### ISSUE THREAD

**Issue by j-griffith** [NetApp/cake#6]
The tool currently has the ability to specify an OVA but it's compiled in the code, it would be handy to provide a config variable to specify the location of alternate/custom OVAs that could be used without needing to modify the code.

**Comment by jacobweinstock** [comment]
this capability has been added with https://github.com/NetApp/cake/pull/36. OVAs for k8s nodes and CAPI load balancers can be specified in the config file like this:

```bash
OVA:
  NodeTemplate: "http://storage.googleapis.com/capv-images/release/v1.17.3/ubuntu-1804-kube-v1.17.3.ova"
  LoadbalancerTemplate: "http://storage.googleapis.com/capv-images/extra/haproxy/release/v0.6.0-rc.2/capv-haproxy-v0.6.0-rc.2.ova"
```
